version: '2'
services:
    fastfooddelivery-app:
        image: fastfooddelivery
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fastfooddelivery-postgresql:5432/fastFoodDelivery
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fastfooddelivery-postgresql:
        extends:
            file: postgresql.yml
            service: fastfooddelivery-postgresql
